"use client"

import { Tracker } from "@/components/Tracker"

const data = [
  { color: "bg-emerald-600", tooltip: "Running" },
  { color: "bg-emerald-600", tooltip: "Running" },
  { color: "bg-emerald-600", tooltip: "Running" },
  { color: "bg-red-600", tooltip: "Error" },
  { color: "bg-emerald-600", tooltip: "Running" },
  { color: "bg-emerald-600", tooltip: "Running" },
  { color: "bg-emerald-600", tooltip: "Running" },
  { color: "bg-red-600", tooltip: "Error" },
  { color: "bg-emerald-600", tooltip: "Running" },
  { color: "bg-emerald-600", tooltip: "Running" },
  { color: "bg-emerald-600", tooltip: "Running" },
  { color: "bg-emerald-600", tooltip: "Running" },
  { color: "bg-emerald-600", tooltip: "Running" },
  { color: "bg-emerald-600", tooltip: "Running" },
  { color: "bg-emerald-600", tooltip: "Running" },
  { color: "bg-emerald-600", tooltip: "Running" },
  { color: "bg-yellow-600", tooltip: "Warn" },
  { color: "bg-emerald-600", tooltip: "Running" },
  { color: "bg-emerald-600", tooltip: "Running" },
  { color: "bg-emerald-600", tooltip: "Running" },
  { color: "bg-emerald-600", tooltip: "Running" },
  { color: "bg-emerald-600", tooltip: "Running" },
  { color: "bg-emerald-600", tooltip: "Running" },
  { color: "bg-emerald-600", tooltip: "Running" },
  { color: "bg-emerald-600", tooltip: "Running" },
  { color: "bg-emerald-600", tooltip: "Running" },
  { color: "bg-emerald-600", tooltip: "Running" },
  { color: "bg-emerald-600", tooltip: "Running" },
  { color: "bg-emerald-600", tooltip: "Running" },
  { color: "bg-emerald-600", tooltip: "Running" },
  { color: "bg-emerald-600", tooltip: "Running" },
  { color: "bg-emerald-600", tooltip: "Running" },
  { color: "bg-emerald-600", tooltip: "Running" },
  { color: "bg-emerald-600", tooltip: "Running" },
  { color: "bg-emerald-600", tooltip: "Running" },
  { color: "bg-emerald-600", tooltip: "Running" },
  { color: "bg-emerald-600", tooltip: "Running" },
  { color: "bg-emerald-600", tooltip: "Running" },
  { color: "bg-emerald-600", tooltip: "Running" },
  { color: "bg-emerald-600", tooltip: "Running" },
  { color: "bg-emerald-600", tooltip: "Running" },
  { color: "bg-emerald-600", tooltip: "Running" },
  { color: "bg-emerald-600", tooltip: "Running" },
  { color: "bg-emerald-600", tooltip: "Running" },
  { color: "bg-emerald-600", tooltip: "Running" },
  { color: "bg-emerald-600", tooltip: "Running" },
  { color: "bg-emerald-600", tooltip: "Running" },
]

export const Tracker1 = () => <Tracker data={data} />
